
networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - ./healthchecks:/healthchecks

    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    networks:
      - stack

  calcom:
    image: "${TESTING_IMAGE}"
   
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calcom
      DATABASE_HOST: database:5432
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      calcom:
        condition: service_started
      postgres:
        condition: service_healthy
    # run all your tests here against the allhands22 service
    command: curl --fail http://calcom:3000 || exit 1
    
