
networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - ./healthchecks:/healthchecks

    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s 



    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    networks:
      - stack

  calcom:
    image: "${TESTING_IMAGE}"
   
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000

    healthcheck:
      test: curl --fail http://calcom:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s 

    environment:
     
      DATABASE_URL: postgresql://postgres:postgres@database:5432/calcom
    depends_on:
      database:
        condition: service_healthy
  
  # sut:
  #   image: "${TESTING_IMAGE}"
  #   depends_on:
  #     calcom:
  #       condition: service_healthy
      
    # command: |
    
    #  curl --fail http://calcom:3000  || exit 1
    
