

networks:
  stack:
    name: stack
    external: false

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks

    healthcheck:
      test:  /healthchecks/postgres-healthcheck
      interval: "5s"
    networks:
      - stack
    

  calkube:
    image: "${TESTING_IMAGE}"
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
   
    environment:
    
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/calcom
    depends_on:
      - postgres

    
  
 
 
   
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      calkube:
        condition: service_healthy
      postgres:
        condition: service_healthy
   
    command:  curl --fail-with-body http://calkube:3000 || exit 1
    