
services:
  calkube:
    image: "${TESTING_IMAGE}"
   
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/calcom
    
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: integration-test/postgres-healthcheck
      interval: "5s"
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      calkube:
        condition: service_healthy
      # postgres:
      #   condition: service_completed_successfully
    # run all your tests here against the calkube service
    command:  curl --fail-with-body http://calkube:3000 || exit 1
    