
services:
  postgres:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks

    healthcheck:

      interval: 10s
      timeout: 5s
      retries: 5
  
    

  calkube:
    image: "${TESTING_IMAGE}"
    restart: always
  
    ports:
      - 3000:3000
   
    environment:
    
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/calcom
    depends_on:
      - postgres

    
  
 
 
   
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      calkube:
        condition: service_started
      # postgres:
      #  condition: service_healthy
  
    command:  curl --fail http://calkube:3000 || exit 1
  
     
          # echo "Waiting for the server to start..."
          #   sleep 120

          #  for i in {1..60}; do
          #     echo "Checking server health ($i/60)..."
          #     response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
          #     echo "HTTP Status Code: $response"
          #     if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
          #       echo "Server is healthy"
          #       # Now, shutdown the server
          #       kill $server_pid
          #       exit 0
          #     fi
          #     sleep 1
          #   done
        
          #   echo "Server health check failed"
          #   kill $server_pid
          #   exit 1
    