

# networks:
#   stack:
#     name: stack
#     external: false

services:
  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./healthchecks:/healthchecks

  #   healthcheck:
  #     test:  infra/docker/web/integration-test/healthchecks/postgres-healthcheck
  #     interval: "5s"
  #   networks:
  #     - stack
    

  calkube:
    image: "${TESTING_IMAGE}"
    restart: always
    # networks:
    #   - stack
    ports:
      - 3000:3000
   
    environment:
    
      - DATABASE_URL=postgresql://localUser:localPassword@localhost:5432/test
    # depends_on:
    #   - postgres

    
  
 
 
   
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      calkube:
        condition: service_healthy
      # postgres:
      #   condition: service_healthy
   
    command: |
  
     --interval=30s --timeout=30s --retries=5 \
     wget --spider http://localhost:3000 || exit 1
    