

networks:
  stack:
    name: stack
    external: false

services:
  calkube:
    image: "${TESTING_IMAGE}"
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_HOST=postgres:5432
      - POSTGRES_DB=calcom
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - postgres

    
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /infra/docker/web/integration-test/healthchecks:/healthchecks

    healthcheck:
      test: integration-test/postgres-healthcheck
      interval: "5s"
    networks:
      - stack
    
 
   
  
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      calkube:
        condition: service_healthy
      postgres:
        condition: service_healthy
   
    command:  curl --fail-with-body http://calkube:3000 || exit 1
    