apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-password
                  key: db-password 
          ports:
            - containerPort: 5432
              name: postgres    
        
      